{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-azurefile-node-sa
  namespace: {{ .Release.Namespace }}
{{ include "azurefile.labels" . | indent 2 }}
{{- end -}}
